[package]
name = "reminder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
cron = "0.12.0"
notify-rust = "4"
serde = "1.0.188"
serde_derive = "1.0.188"
toml = "0.8.1"
